### ISSUE TITLE
IInferenceParams does not contain a definition for MinP

### ISSUE THREAD

**Issue by Webslug** [saddam213/LLamaStack#5]
I tried to run the example but encountered this error in LlamaStackContext.cs.  I've installed everything and I'm using the latest version of LlamaSharp.  

'IInferenceParams' does not contain a definition for 'MinP' and no accessible extension method 'MinP' accepting a first argument of type 'IInferenceParams' could be found (are you missing a using directive or an assembly reference?)	LLamaStack.Core	C:\Users\Me\source\repos\LLamaStack-master\LLamaStack.Core\LLamaStackContext.cs	143	Active
```

        public int Sample(LLamaTokenDataArray tokenDataArray, IInferenceParams inferenceParams, ref float? mirostatMu)
        {
            return _context.Sample
            (
                tokenDataArray,
                ref mirostatMu,
                inferenceParams.Temperature,
                inferenceParams.Mirostat,
                inferenceParams.MirostatTau,
                inferenceParams.MirostatEta,
                inferenceParams.TopK,
                inferenceParams.TopP,
                inferenceParams.TfsZ,
                inferenceParams.TypicalP,
                inferenceParams.Grammar,
                inferenceParams.MinP
            );
        }
```

I also get the following errors when trying to start the WPF example.

The type reference cannot find a public type named 'SessionHistoryModel'. Line 116 Position 90.	LLamaStack.WPF	C:\Users\Me\source\repos\LLamaStack-master\LLamaStack.WPF\Views\InferenceView.xaml	116	

The type reference cannot find a public type named 'ModelSessionState`1'. Line 34 Position 82.	LLamaStack.WPF	C:\Users\Me\source\repos\LLamaStack-master\LLamaStack.WPF\Views\SessionLoadView.xaml	34	

![llamasharp](https://github.com/saddam213/LLamaStack/assets/7551638/5a811160-dc44-427f-b8ca-b1bb38f49ca4)

**Comment by saddam213** [comment]
Hey Webslug,

The `LLamaStack` master branch in in sync with rhe `LLamaSharp` master branch, so you would need to clone that repo if you want to use the features in master.

Alternativly you can checkout commit [1bc8917](https://github.com/saddam213/LLamaStack/commit/1bc8917b79615df27590544f9df4862bb55a66fa)

Or simply comment out the offending line `//inferenceParams.MinP`

**Comment by saddam213** [comment]
No Response, closing
